#page title
page_title                                : GeoTip - Find tips near you                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1615652784                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://testflight.apple.com/join/kCeS9Hut                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : GeoTip                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Find tips in your local community.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Kelden Lin                                
your_link                                 : http://keldenl.com/                     
your_city                                 : Seattle, WA                                
email_address                             : keldenlin@gmail.com
facebook_username                         :                                           
instagram_username                        : keldenl
twitter_username                          : keldenlin
github_username                           : keldenl
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

# - There isn’t a landmark requirement, which means a restaurant or location name isn't required to make a tip at that certain location.
#     - A good example of utilizing this is adding tips in specific areas in a mountain or a hike, or a general tip that describes a whole area/neighborhood
# - Search for a specific landmark to find tips ahead of time of places you’re going to go (supported by OpenMaps) 
# - Upvote existing tips to increase legitimacy of that tip
# - Report tips that are spam / violations of terms of service
# - Sign in and create an account to do all actions above (viewing doesn’t require an account) securely with “Sign in with Apple” 
# - Introduction of “FourWord” – a brand new alternate latitude/longitude representation with 4 english words
#     - Use this to search for and create tips at easily sharable locations

  - title                                 : Quickly create local tips
    description                           : View and create short tips based off your current or a specific location
    fontawesome_icon_name                 : sticky-note

  - title                                 : Flexibile and unlimited possibilities
    description                           : No place name is required – tips aren't associated with a specific restaurant or place
    fontawesome_icon_name                 : magic
    
  - title                                 : Sign in with Apple
    description                           : Sign in securely with Apple to create and upvote tips
    fontawesome_icon_name                 : user
    
  - title                                 : Introducing "FourWord"
    description                           : New alternate latitude/longitude representation with 4 english words – supported throughout the app
    fontawesome_icon_name                 : map
    
  - title                                 : Get useful tips
    description                           : Upvote existing tips to increase legitimacy
    fontawesome_icon_name                 : arrow-up
    
  - title                                 : Scout ahead
    description                           : Search for places you're visiting to find tips ahead of time
    fontawesome_icon_name                 : search
    
  # - title                                 : iPhone Device Preview
  #   description                           : Preview your app in the context of an iPhone device. Five different device colors included.
  #   fontawesome_icon_name                 : mobile

  # - title                                 : Video Support
  #   description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
  #   fontawesome_icon_name                 : play-circle

  # - title                                 : Automatic Icon and Metadata
  #   description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
  #   fontawesome_icon_name                 : sync

  # - title                                 : Easy to Tweak
  #   description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : adjust
  
  # - title                                 : Feature List
  #   description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : star

  # - title                                 : Smart App Banner
  #   description                           : Display a smart app banner on iOS devices.
  #   fontawesome_icon_name                 : arrow-alt-circle-down

  # - title                                 : Social Links
  #   description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : link

  # - title                                 : FontAwesome Support
  #   description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : info-circle

  # - title                                 : # New Feature Title
  #   description                           : # New Feature Description
  #   fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
